### ISSUE TITLE
Understanding the data format

### ISSUE THREAD

**Issue by matt-dejavu** [visjs/angular-visjs#1]
$scope.data = visDataSet({
     "1": {
       "id": 1,
       "content": "<i class=\"fi-flag\"></i> item 1",
       "start": "2014-09-01T17:59:13.706Z",
       "className": "magenta",
       "type": "box"
     },

This doesn't make a whole lot of sense. Why is this not merely an array of timeline items? How would I generate this from an array of data items? It's the "1", "2", "3" part I don't understand. If I'm looping through an array of my data to generate the timeline items, how do I convert i to a string and insert it as the name of a property? This seems to only work with static data, not with data that might come from a service, for example.

**Comment by cdjackson** [comment]
I'll close this since the data set is now the standard visjs version
