### ISSUE TITLE
data.load for timeline

### ISSUE THREAD

**Issue by y-lohse** [visjs/angular-visjs#15]
Hi, just wondering about the reason why items & groups for timelines have to be inside a subobject called `load` (https://github.com/visjs/angular-visjs/blob/master/angular-vis.js#L48)? Wouldn't it make more sense for them to just be at the root level?

**Comment by cdjackson** [comment]
This is still the old directive where there was a strange version of the dataSet object. For the newer version which I’m testing at the moment, and as per the graph2D, it doesn’t do this.

**Comment by y-lohse** [comment]
Ok, cool, thanks :). Is the newer version accessible somewhere? Haven't seen it in the branches.

**Comment by cdjackson** [comment]
No - I’ve been mainly focussing on the graph2d, and only started to play with the timeline this week. Currently it’s nearly the same as the graph2d implementation - I’ll add it to the development repo tonight or tomorrow if I get time.

**Comment by cdjackson** [comment]
I've pushed the changes to the development branch, and also updated the example at http://visjs.github.io/angular-visjs/#/timeline

**Comment by y-lohse** [comment]
Awesome, thanks!
