### ISSUE TITLE
Network graph Using nested JSON and AngularJS 

### ISSUE THREAD

**Issue by shadi-mahm** [visjs/angular-visjs#17]
I've created simple network graph based on a json file containing nodes and edges. now I want to use another json data which includes an array with members that have children. I'm just confused how can I change the directive to show such a graph.

**Comment by josdejong** [comment]
How does your data look like?

**Comment by shadi-mahm** [comment]
Hi Jos,
I sent you an email yesterday, thank you for the reply but I couldnt go further with the wrapper you mentioned. I put both data and directive here.

The new json I want to use : https://github.com/shadi-mahm/BOM-Graph/blob/master/new.json
Directive: https://github.com/shadi-mahm/BOM-Graph/blob/master/Scripts/bomGraph.js
Controller: https://github.com/shadi-mahm/BOM-Graph/blob/master/Scripts/app.js
Old json that works with the code: https://github.com/shadi-mahm/BOM-Graph/blob/master/data.json

**Comment by josdejong** [comment]
Network does not work with a nested data structure, but with two flat arrays as in your "old json". If your data contains a nested structure, you first have to convert this into the data structure that Network expects: one Array with nodes and one with edges.

I guess for your new data structure you can extract the edges with a loop like:

```js
var edges = [];
nodes.forEach(function (node) {
  node.children.forEach(function (child) {
    edge.push({from: node.id, to: child.childId});
  });
});
```

**Comment by shadi-mahm** [comment]
Thank you Jos, I try it now.
