### ISSUE TITLE
Documentation doesn't reflect installation.  

### ISSUE THREAD

**Issue by matthewharwood** [visjs/angular-visjs#19]
The bower install line is wrong.
The package also doesnt include visjs vanilla. which throws this error

Stack trace
```
ReferenceError: vis is not defined
    at new <anonymous> (http://localhost:9000/bower_components/angular-visjs/angular-vis.js:7:24)
```
angular-vis.js

```
.factory('VisDataSet', function () {
        'use strict';
        return function (data, options) {
            // Create the new dataSets
            return new vis.DataSet(data, options);
        };
    })
```
stacktrack #2 
```
  at new <anonymous> (http://localhost:9000/scripts/controllers/main.js:13:21)
```

MainCtrl
```
  .controller('MainCtrl', function ($scope, VisDataSet) {
 
    var dataItems = new VisDataSet();
    dataItems.add([{}]);
    $scope.graphData = {
      items: dataItems,
      groups: dataGroups
    };
  });
```

**Comment by cdjackson** [comment]
If the error is vis is not defined, then it probably means you haven’t included the vis library? I haven’t specified this in the tutorial (I’ll update it) but clearly you need to include files like angular, angular-visjs and vis itself. If you have this included, then I’d suggest trying the demo to see if that works?

**Comment by matthewharwood** [comment]
Hey Yeah man.  I figured it out after a few mins.  Also could you add to your documentation to 
add VisDataSet factory to controller
```
angular.module('myApp')
  .controller('MainCtrl', function (VisDataSet) {});
```
As this maybe helpful.

**Comment by cdjackson** [comment]
Will do - thanks.
