### ISSUE TITLE
Working example requested

### ISSUE THREAD

**Issue by fennekit** [visjs/angular-visjs#24]
The example in the root of the repository does not work with the version of angular-vis.js. 

Cannot find the code of the example inhttp://visjs.github.io/angular-visjs/#/home

I would like to use it, but with no working example the effort needed to get something working is too high.

**Comment by cdjackson** [comment]
Please take a look at the example in the github pages branch (gh-pages). There is a working example here (http://visjs.github.io/angular-visjs/#/home)

**Comment by fennekit** [comment]
Nice. Will look at it tonight.

**Comment by fennekit** [comment]
Demo in branch gh-pages works perfectly. Thanks
