### ISSUE TITLE
AngularJS 2.0?

### ISSUE THREAD

**Issue by Tooa** [visjs/angular-visjs#31]
Hi,

does this also work with the current dev version of angularjs 2.0? Would be nice to have a working version, but I think it's too much effort to maintain due to likely breaking changes.

**Comment by cdjackson** [comment]
I’ve not tried it - if you try, let me know… I probably won’t change to Angular 2 for a bit, but when things are stable(ish!) I might be tempted to add support, but I guess it will be a significant change…

**Comment by Tooa** [comment]
Hi,

thanks for the answer. Then I will probably stay with angularjs 1.4. I've tried the visjs directive with angular 1.4 and the new router. However, can't get it to work. I assume the directive has nothing to to with the new router. Can you please have a look at the code [here](https://github.com/Tooa/angular-visjs-playground). It's everything you need, just run "http-server". The  home component contains the graph.

**Comment by Tooa** [comment]
Thanks you. I guess, I will follow your advice and stay with Angular 1.4 for a while then.

**Comment by TekSiDoT** [comment]
A year has passed and Angular2 has made huge steps, are you tempted to add support? ;)

**Comment by cooervo** [comment]
Please add angular 2 support

**Comment by Tooa** [comment]
There is a new Angular 2 wrapper [here](https://github.com/almende/vis/issues/2242). It is still in development, but you guys might check it out and consider giving feedback during the development process.

**Comment by seveves** [comment]
I am currently working on the network component (just started this weekend) and then I will push a first alpha on npm and would be happy to receive a lot of feedback. Feel free to contribute in any way!

**Comment by mojoaxel** [comment]
here is the link https://github.com/seveves/ng2-vis
