### ISSUE TITLE
selectEdge Event is not fired

### ISSUE THREAD

**Issue by Tooa** [visjs/angular-visjs#33]
Hi, 

the selectEdge event is not fired, when clicking on an edge. The click event though is working!

<b>Not working</b>
`$scope.graphEvents = {
        "selectEdge": function(params) { console.log('selectEdge Event:', params); }
    };`

<b> Working </b>
`$scope.graphEvents = {
        "click": function(params) { console.log('click Event:', params); }
    };`

**Comment by cdjackson** [comment]
What directive is this for? Network?

**Comment by cdjackson** [comment]
Please try the latest version (not from bower - download off github)

**Comment by Tooa** [comment]
Yes, the issue is about the network directive. It seems that it's simply not implemented. Newest GitHub source code [here](https://github.com/visjs/angular-visjs/blob/master/angular-vis.js) 

```javascript
if (['select', 'click', 'hoverNode', 'doubleClick'].indexOf(String(event)) >= 0) {
                            network.on(event, callback);
 }
```

Your latest commit adds the events to the Timeline component. It also looks like there is another copy paste mistake. The network directive has the same name events as the timeline component. See line `114f`:

```javascript
var networkEvents = [
                    'rangechange',
                    'rangechanged',
                    'timechange',
                    'timechanged'
                ];
```

**Comment by cdjackson** [comment]
Sorry - should be in teh right place now.

**Comment by Tooa** [comment]
Works great now. Thanks! Closing this issue as the problem is fixed.
