### ISSUE TITLE
angular-vis module doesn't work with requirejs

### ISSUE THREAD

**Issue by Tooa** [visjs/angular-visjs#34]
Hi, 

In combination with requirejs the module yields the following error:

    ReferenceError: vis is not defined
    at new <anonymous> (angular-vis.js:7)
    at new <anonymous> (HomeController.js:15)
    at Object.invoke (angular.js:4426)
    at $get.extend.instance (angular.js:8945)
    at nodeLinkFn (angular.js:8075)
    at compositeLinkFn (angular.js:7514)
    at nodeLinkFn (angular.js:8108)
    at compositeLinkFn (angular.js:7514)
    at compositeLinkFn (angular.js:7518)
    at nodeLinkFn (angular.js:8108)

Beginning of the HomeController looks like:

    define([
	'angular',
        'ngMaterial',
        'vis',
        'ngVis'
    ], function(angular) {
	    'use strict';

       angular.module('myApp.home', ['ngMaterial', 'ngVis']);
       angular.module('myApp.home').controller('HomeController', ['$scope', '$mdDialog', 'VisDataSet',     function ($scope, $mdDialog, VisDataSet) {

I appreciate any help. Angularjs is relative new for me, so even a quick fix is ok.

**Comment by Tooa** [comment]
After some more digging I was finally able to solve the problem. I missed the dependencies for the `angular-visjs` file:

```javascript
define([
    'angular',
    'vis',
], function(angular, vis) {
    'use strict';

    angular.module('ngVis', [])

    .factory('VisDataSet', function () {
        'use strict';
        return function (data, options) {
            // Create the new dataSets
            return new vis.DataSet(data, options);
        };
    })
```

Closing this issue then.

**Comment by Devqon** [comment]
Thank you I had the exact same problem. But I don't think this would be the most reasonable solution? what is the 'normal' way to do this? what if requirejs isn't used? then this wouldn't work right?
