### ISSUE TITLE
Hooking network click event causes exception

### ISSUE THREAD

**Issue by Tooa** [visjs/angular-visjs#35]
Hi,

as the title says. To get rid of this problem simple remove the following unnecessary code:

    scope.$watch('events', function (events) {
           angular.forEach(events, function (callback, event) {
               if (['select', 'click', 'hoverNode', 'doubleClick'].indexOf(String(event)) >= 0) {
                     network.on(event, callback);
                }
          });
     });

The problem originates from the change in #33

**Comment by cdjackson** [comment]
Hi,
I’m currently away for a few days, but will be back tomorrow. I’ll take a look at this as soon as I can in the next few days).

Cheers
Chris

**Comment by cdjackson** [comment]
Thanks. I don't think this originates from #33 - it's a hangover from an older systen for hooking the events into vis, however you're right, the code is redundant.

Thanks
Chris

**Comment by cdjackson** [comment]
Are you happy if this is closed now?

**Comment by Tooa** [comment]
Sure, we can close the issue.

**Comment by cdjackson** [comment]
Thanks.
