### ISSUE TITLE
How to call methods?

### ISSUE THREAD

**Issue by marfnk** [visjs/angular-visjs#36]
I don't get how you call methods on the timeline graph inside your controller.
You only have `$scope.data`, `$scope.events` and `$scope.options`.

In particular, I like to zoom to a specific window with
`setWindow(start, end [, options])` (from: http://visjs.org/docs/timeline/#Methods)

**Comment by cdjackson** [comment]
You can use the onload() event to get the graph/timeline object, and then you can use this to call the vis methods.

**Comment by richardxy** [comment]
Hi, cdjackson,
Thanks for your work. Would you please give out an example of how to use onload() event to pass the graph/network object to $scope? I'm also having the problem. 

Many thanks,
Richard

**Comment by richardxy** [comment]
I've got it. Only need to define a $scope.events.onload = function (network) { ... } function. Thanks.

**Comment by ASimpson87** [comment]
Hi  , i am using $scope.events.onload = function (timeline){ timeline.addCustomTime(now)}; but it's giving me this error..TypeError: Cannot set property 'onload' of undefined .. any solution?

**Comment by ASimpson87** [comment]
All good sorry , solved it by declaring events with var events = {};. Is this repo still maintained?

**Comment by cdjackson** [comment]
Yes - still maintained. Most development of course is in the library itself.

**Comment by ASimpson87** [comment]
any idea why this is throwing an error? 

$scope.onTimeChange = function (timeline){
$scope.customTime = timeline.getCustomTime();
console.log($scope.customTime)
}
Uncaught TypeError: timeline.getCustomTime is not a function(…)

This works in my $scope.onLoaded = function (timeline){
} function...

**Comment by cdjackson** [comment]
Hard to say. I’d run through the debugger and check what the scope is when it runs, and check what ‘this’ is as well. Maybe it’s running with a different scope, or ’this' than you expect, especially if it’s run from an event.

**Comment by ASimpson87** [comment]
So it should be working? , I'm just not sure i understand what onload() is doing compared to the other event listeners. 

Does onload() grab the timeline object? do i need to use it every time i want to do something within the timeline object? Or if i get an onClick event do i need to then call onLoaded ?
