### ISSUE TITLE
Timeline directive: redraw fails on data change

### ISSUE THREAD

**Issue by sazl** [visjs/angular-visjs#38]
Hi, having an issue with data changes and redrawing the timeline.
When data changes in angular, the directive fails to redraw with the following error.
Setting data for the first time works as expected but any change to the bound data and the directive fails to redraw.

```
Error: Cannot redraw item: no parent attached
    at o.redraw (vis.min.js:31)
    at o.show (vis.min.js:31)
    at o.<anonymous> (vis.min.js:28)
    at Object.e.forEach (vis.min.js:25)
    at vis.min.js:28
    at o.getItemRange (vis.min.js:28)
    at o.fit (vis.min.js:28)
    at o.setItems (vis.min.js:28)
    at o (vis.min.js:28)
    at Object.fn (angular-vis.js:52)
```

Using the following:

```
Angular: 1.4.1
visjs: 4.2.0
angular-visjs: git master branch
```

**Comment by cdjackson** [comment]
To me this looks like a vis problem rather than an angular problem. Does this work if you do the same thing in a basic ‘non angular’ example?

**Comment by sazl** [comment]
Works just fine when not using angular. The plain Javascript library doesn't have this problem:

https://gist.github.com/sazl/60186fefec675a3b282c

I'm guessing it's some problem with the jquery container element that angular passes to the library?

**Comment by cdjackson** [comment]
Ok - thanks. I’ll see if I can find time to take a look over the next few days… Do you have an example that shows the bug using the directive?

**Comment by sazl** [comment]
Hi, turns out that I was passing an improperly structured "groups" collection to the timeline data attribute. Everything works as expected. Sorry for the waste of time and thank you for all your work on the project.

**Comment by serge144** [comment]
Hi,

could you explain how you fixed this? because im having the same error when i call the following method:
timeline.setItems(items)

Is it because you're adding an item to a group that doesn't exist?

Best Regards

**Comment by serge144** [comment]
Answer to my question: Just had to check if the group actually exists when it comes to adding an item with a particular group ID.
