### ISSUE TITLE
timeline.fit() cuts off box items with align: left

### ISSUE THREAD

**Issue by IckleChris** [visjs/angular-visjs#42]
When displaying box items on the timeline with left-aligned branches the `fit()` function doesn't take the repositioned box into consideration, cutting off the last items. Is there the ability to fit the item boxes as well as the timeline points?
<img width="741" alt="timeline_issue_1" src="https://cloud.githubusercontent.com/assets/3933176/10843772/d84ad3d8-7ef2-11e5-9e9c-38351d9cd09b.png">

On a side note, is the refactoring of this repo still in progress? Thanks.

**Comment by cdjackson** [comment]
Are you sure that this is an issue with the directive, and not the way that the vis library works? I don’t think that the directive sizes the DOM container, so I think that this is just the way that the library works in which case you should raise the issue against the main visjs repository…
