### ISSUE TITLE
How to enable editable.remove?

### ISSUE THREAD

**Issue by kuravih** [visjs/angular-visjs#45]
How do I enable `remove` option so I can delete items from the timeline? I've tried `editable: {remove: true }` but nothing happens.

**Comment by josdejong** [comment]
That's indeed the correct way: `editable: {remove: true}`. I'm not sure why this doesn't work in the angular-directive.

**Comment by kuravih** [comment]
I had a `* {overflow-x: hidden;}` for a different reason, so `.vis-item{overflow-x:visible !important;}` fixed it, thanks.
