### ISSUE TITLE
Network: invert mouse on zoom

### ISSUE THREAD

**Issue by antonbagayev** [visjs/angular-visjs#49]
Hi,

Thanks for your recent implementation of image interpolation for nodes. Looks great!

Not sure it's possible with the current implementation, but would it be a lot of work to add the ability to invert mouse for zoom interactions (e.g. via Network options), so that wheel scroll-down actually zooms in instead of out, and vice-versa?

Thank you,
Anton.

**Comment by cdjackson** [comment]
Is this an angular vis issue, or a question for the main vis library? I suspect the library?

**Comment by antonbagayev** [comment]
Oh, apologies... I mixed up the two git pages.

**Comment by cdjackson** [comment]
No probs :)
