### ISSUE TITLE
Drawing a dotted line( Edge ) between 2 nodes which are in 2 different networks.

### ISSUE THREAD

**Issue by esh-cherukuri** [visjs/angular-visjs#51]
Hi,

I need to draw a dotted line between 2 nodes which are in 2 different networks.
Here is the jsfiddle link : https://jsfiddle.net/eshch/6mwtgf3u/
In that link you can see there are 4 nodes in network1 and 3 nodes in network2  ( all the node id's are same ) now i need to draw a dotted edge from node1 in network 1 to node 1 in network 2 is that possible. If not how can we do that.

Many many thanks in advance.

**Comment by cdjackson** [comment]
I'd suggest to take a look at the vis documentation (http://visjs.org/). They also have a lot of good example of many different configurations, and very good documentation on how to set different attributes of the lines etc...

**Comment by esh-cherukuri** [comment]
There is no example to show an edge between 2 nodes in 2 different networks.

**Comment by AlexDM0** [comment]
Hi, since you already asked this on the vis github page, let's focus the discussion there.

**Comment by esh-cherukuri** [comment]
Sure. Thank you.
