### ISSUE TITLE
align: 'left' doesn't work

### ISSUE THREAD

**Issue by mengli0315** [visjs/angular-visjs#52]
in options:
getOptions: ()->
    {
      autoResize: true  
      align: 'left'
      …
    }
align: 'left' does not work

then i try to set nodeset like below, still not work
nodeset = [
      {
        id: 1
        label: 'status: ' + general.status 
        shape: 'text'
        size: 30
        align: 'left'
      }
  ]
What am I doing wrong?

**Comment by josdejong** [comment]
Should be `{font: {align: 'left'}}`

See this example: http://visjs.org/examples/network/labels/labelAlignment.html

**Comment by mengli0315** [comment]
@josdejong 
I've tried follow the example：
nodeset = [
{
id: 1
label: 'general '
shape: 'box'
size: 30
font: {align: 'left'}
}
then the label text run out of the 'box'
![image](https://cloud.githubusercontent.com/assets/15190661/13766595/2c98e9cc-ea9e-11e5-96a9-73a8fb3b87f5.png)

**Comment by mengli0315** [comment]
it work well after upgrade to the latest version, thanks.
