### ISSUE TITLE
It's possible to display a Streaming graph ?

### ISSUE THREAD

**Issue by sboub95** [visjs/angular-visjs#53]
VisJs make a streaming graph -> http://visjs.org/examples/graph2d/15_streaming_data.html
it's possible with your repo ?

thanks

**Comment by cdjackson** [comment]
Sure. The angular directive just provides access to the bus component, so you can do all the same things.

**Comment by sboub95** [comment]
Ok.
So it is not already developed, we have to adapt what is already developed, compared to alternative graphics library "VisJs"?
Thanks.

**Comment by cdjackson** [comment]
The angular directive allows you to access the vis library, so just use the same example from vis. Note that these are examples - they shoutout how to do something and aren't intended to be a fully fledged end user tool. 

As a developer, you should develop something from that ;)
