### ISSUE TITLE
Graph2d graph doesn't seem working

### ISSUE THREAD

**Issue by bimalthapa** [visjs/angular-visjs#9]
Could you show how to implement graph2d? 

What I did is: 
in html:  <vis ng-transclude><graph-2d data="data" options="options"></graph-2d></vis>
in controller: 
$scope.options = {
 style: 'line',
 start: '2014-06-10',
 end: '2014-06-18'
};
var items = [
      {x: '2014-06-11', y: 10},
      {x: '2014-06-12', y: 25},
      {x: '2014-06-13', y: 30},
      {x: '2014-06-14', y: 10},
      {x: '2014-06-15', y: 15},
      {x: '2014-06-16', y: 30}
];
$scope.data = visDataSet(items);

Let me know if I did something wrong here.

**Comment by cdjackson** [comment]
I'll close this since the data set is now the standard visjs version
